### ISSUE TITLE
Reduce `try/catch` Statements (Better Error Handling)

### ISSUE THREAD

**Issue by dino-rodriguez** [payid-org/payid#136]
Currently we have `try/catch` statements all throughout the code returning lots of different kinds of errors. Ideally this error handling is refactored to make the code more readable.

A few possible approaches:
- Error handling helpers that contain `try/catch`
- Catching errors at the lowest levels (in the database layer services for example), and returning Either Monads in those functions

**Comment by hbergren** [comment]
There are basically no `try catch` statements in the codebase anymore, because we've completely refactored error handling.

I'm calling this a win.
