### ISSUE TITLE
Update docs to correct path to "demo" folder

### ISSUE THREAD

**Issue by rswarthout** [payid-org/payid#533]
The docs located at ( https://docs.payid.org/remote-deployment/ ) refer to a demo folder and a script within. The folder does not appear anywhere within the repo.

## Detailed Description

Missing "demo" folder that docs refer to. At one point it seems it was renamed to "example" but that too has been removed in commit ( https://github.com/payid-org/payid/commit/34fef51ecd1e5faa6a117c604b7114496bfdd2b9 ). 

## Context

I am trying to step through the docs to set up a server on AWS and the folder is missing.

**Comment by dino-rodriguez** [comment]
Thank you for bringing this to our attention! @rswarthout 

We are updating the docs to reflect more appropriate instructions.

For now, I would recommend that you run `npm run devEnvUp` in place of those commands.

And chance the port range in the `docker-compose.yml` file in the root directory from:

`8080:8080` to `80:8080`
