### ISSUE TITLE
Can't run devDbUp, missing script

### ISSUE THREAD

**Issue by antmikinka** [payid-org/payid#569]
## Expected Behavior

Install Docker and clone repository
Install gitBash, Node.js
run devDbUp
Start working

## Actual Behavior

Installed Docker, Node.js, and Git Bash. 
Try npm run devDbUp
Says missing "script"

## Context

This issue has pervented me from starting to worrk and develop.
I had as my first issue not having my SSH keys connected to github I fixed that then I had to create a package.json file in my users. After I did that my new issue was that I could not run "npm run devDbUp" or "npm run devEnvUp".

## Steps to Reproduce

1. Install Git Bash and Node.js
2. run: npm install
3. run: npm install  https://github.com/payid-org/payid
3. open powershell and run: npm run devEnvUp

## Environment

- Node version: 12.18.1
- NPM version: 6.14.5
- Operating System and version: Windows 10 Pro, 19041.329
- PayID server version: n/a
- PayID Version header (if applicable): n/a

### Screenshots

![image](https://user-images.githubusercontent.com/67480807/85897798-119c8000-b7c9-11ea-9fa1-1b4ddd26bd18.png)

**Comment by hbergren** [comment]
Hey @antmikinka , can you run `npm run devEnvUp` from the `payid` directory (where you cloned the git repository to)?

**Comment by antmikinka** [comment]
Yup that worked! Thank you.
![2020-06-26 (3)](https://user-images.githubusercontent.com/67480807/85901474-f3864e00-b7cf-11ea-97bd-8ba618ae5d97.png)

**Comment by antmikinka** [comment]
While running `npm run devEnvUp` you can see it created a PayID, is that so? I am following the steps on Getting Stared | PayID Developer. I follow the guide to create a PayID then it comes up with this. Am I supposed to put in my own information in the double quotes or just copy and paste into powershell as In have been doing?
![2020-06-26 (4)](https://user-images.githubusercontent.com/67480807/85901997-f5044600-b7d0-11ea-8a69-801626cf239b.png)
![2020-06-26 (5)](https://user-images.githubusercontent.com/67480807/85902004-f766a000-b7d0-11ea-8aa3-55d06e910264.png)

**Comment by hbergren** [comment]
> While running npm run devEnvUp you can see it created a PayID, is that so?

Hi @antmikinka , it just created the `payid` server Docker image or container. I admit that's confusing, so I wrote a PR to rename that Docker service.

> Am I supposed to put in my own information in the double quotes or just copy and paste into powershell?

You can do either, but it looks like the UNIX-style `curl` command isn't the correct syntax for Powershell. You can either adapt the script to be Powershell-compliant, or you could use the Windows Subsystem for Linux to get a UNIX-compatible terminal.

**Comment by antmikinka** [comment]
@hbergren Oh ok thank you. What UNIX-compatible terminal do you use? Sorry I'm a bit of a newbie. I got this error about connection being refused after I copy and paste. Would this have to do with me newly installing Ubuntu (like starting from cloning the repository), would I have to recreate a SSH and add it to GitHub to not have the connection be refused? I tried Ubuntu and GitBash (trying to troubleshoot the issue).
![2020-06-29](https://user-images.githubusercontent.com/67480807/86076984-22fbbb80-ba59-11ea-8338-5bcd0b2a5402.png)
![2020-06-29 (1)](https://user-images.githubusercontent.com/67480807/86076990-255e1580-ba59-11ea-98f1-ab3b545ca7bf.png)

**Comment by hbergren** [comment]
Thanks for including the screenshots! That makes debugging way easier.

> @hbergren Oh ok thank you. What UNIX-compatible terminal do you use?

Hey @antmikinka , I fully switched over to Macbooks so I haven't used Windows 10 in a bit. I got tired of fighting the OS when I had a programming project 😄 

From Googling around it _looks like_ your problem might be the Windows PATH interfering with the WSL PATH. They discuss how to fix that on [this StackOverflow](https://github.com/microsoft/WSL/issues/1890).

If you haven't already, you might also want to walk through the [official Microsoft guide for setting up Node.js development on WSL](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2).

Let me know if either of those resources help you fix your problem. If not, I'm happy to look into more potential solutions.

**Comment by hbergren** [comment]
Hey @antmikinka , were you able to figure this out?
