### ISSUE TITLE
curl: (7) Failed to connect to 127.0.0.1 port 8081: Connection refused

### ISSUE THREAD

**Issue by kencarabello** [payid-org/payid#589]
Hi guys.

I finally got the payid server to run. But now when I run the curl command to create a payID, I get the error shown in the subject field.

## Steps to Reproduce

1. Step one
2. Step two
3. Step three

## Environment

- Node version:
- NPM version:
- Operating System and version:
- PayID server version:
- PayID Version header (if applicable):

## Bonus

**Are you willing to submit a pull request to fix this bug?**

**Comment by kencarabello** [comment]
Sup folks.
I don't want to speak too soon. But it looks like somebody did something. 
I am no longer getting the error message from the PayID server. 
Getting there little by little.
Thanks. 
Peace.

**Comment by kencarabello** [comment]
Hey man.

Nothing that I can think of. Not since yesterday when it wasn't working.
I'm still not all the way to the handshake though. The command just
lingers. But again, no error message at this point.

I won't know until I either talk to AWS and get help, or resolve the EC2
issue on my own. AWS is connecting to PayID. So outbound is fine. But AWS
inbound is hung up.

I'm hoping to get it resolved by tomorrow.

Cheers!

**Comment by hbergren** [comment]
That's great to hear. Do you mind if we close this issue?

**Comment by kencarabello** [comment]
Sure thing. Thanks.
