### ISSUE TITLE
Pull latest Git tag before comparing NPM and Git versions

### ISSUE THREAD

**Issue by nkramer44** [payid-org/payid#606]
## Expected Behavior
Tried pushing when the latest tag I had locally was 1.0.1, but the latest npm version was 1.1.0.  Would expect an automatic pull of the latest git tag.

## Actual Behavior
Pre-push hooks wouldn't allow me to push because the versions were mismatched.

## Context
Not a huge issue, but probably a bad UX for non-xpring contributors who won't be able to open a PR without knowing that they need to pull the latest tag version from git.

## Potential Solution
We could probably just pull the latest tag in the `version.sh` `compare_versions` script.

## Steps to Reproduce

1. Step one
2. Step two
3. Step three

## Environment

- Node version:
- NPM version:
- Operating System and version:
- PayID server version:
- PayID Version header (if applicable):

## Bonus

**Are you willing to submit a pull request to fix this bug?**

**Comment by hbergren** [comment]
@dino-rodriguez , liked we talked about on Friday, we should probably move to a GitHub/GitLab action that:
- Runs the script to detect `package.json` version changes
- Cuts a new GitHub release itself

That way we won't need to run this script locally, and we can avoid contributors getting hit by this.

**Comment by dino-rodriguez** [comment]
@hbergren I agree that's the optimal workflow. I'm going to remove `compareVersions` from the lint script, which should fix this issue.
